// Generated by FakeUnityCLI. Edits invalidate the CLI integrity check.
#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace FakeUnity.EditorBridge
{
    internal static class Core
    {
        internal const string Version = "1.9.0-unity2022.3";

        [Serializable]
        internal sealed class Args
        {
            public string path;
            public string[] paths;
            public string[] scenes;
            public string output_path;
            public string target;
            public string group_name;
            public string schema_type;
            public string profile_name;
            public string variable_name;
            public string value;
            public string rule_name;
            public int options;
        }

        [Serializable]
        internal sealed class Plan
        {
            public string operation;
            public string execute_method;
            public Args arguments;
            public string result_path;
        }

        [Serializable]
        internal sealed class Result
        {
            public string bridge_version = Version;
            public bool success;
            public string operation;
            public string message;
            public string[] artifacts = new string[0];
            public string[] warnings = new string[0];
            public string[] errors = new string[0];
        }

        internal static void Run(Action<Plan, Result> action)
        {
            Result result = new Result();
            string resultPath = null;
            try
            {
                var planPath = CommandLine("-fucPlan");
                if (String.IsNullOrEmpty(planPath) || !File.Exists(planPath))
                    throw new InvalidOperationException("-fucPlan is missing or unreadable.");
                var plan = JsonUtility.FromJson<Plan>(File.ReadAllText(planPath));
                if (plan == null || String.IsNullOrEmpty(plan.operation))
                    throw new InvalidOperationException("Plan JSON is invalid.");
                plan.arguments = plan.arguments ?? new Args();
                result.operation = plan.operation;
                resultPath = String.IsNullOrEmpty(plan.result_path) ? planPath + ".result.json" : plan.result_path;
                action(plan, result);
                result.success = true;
                if (String.IsNullOrEmpty(result.message)) result.message = "completed";
            }
            catch (Exception ex)
            {
                result.success = false;
                result.message = ex.Message;
                result.errors = new[] { ex.ToString() };
            }

            if (!String.IsNullOrEmpty(resultPath))
            {
                Directory.CreateDirectory(Path.GetDirectoryName(resultPath));
                File.WriteAllText(resultPath, JsonUtility.ToJson(result, true));
            }
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            EditorApplication.Exit(result.success ? 0 : 1);
        }

        internal static string CommandLine(string key)
        {
            var args = Environment.GetCommandLineArgs();
            for (var i = 0; i + 1 < args.Length; i++)
                if (args[i] == key) return args[i + 1];
            return null;
        }

        internal static Type TypeByName(string fullName)
        {
            var type = AppDomain.CurrentDomain.GetAssemblies()
                .Select(a => a.GetType(fullName, false)).FirstOrDefault(t => t != null);
            if (type == null) throw new InvalidOperationException("Required Editor API is unavailable: " + fullName);
            return type;
        }

        internal static object AddressableSettings()
        {
            var type = TypeByName("UnityEditor.AddressableAssets.Settings.AddressableAssetSettingsDefaultObject");
            var settings = type.GetProperty("Settings", BindingFlags.Public | BindingFlags.Static).GetValue(null, null);
            if (settings == null) throw new InvalidOperationException("Addressables settings asset is not configured.");
            return settings;
        }

        internal static MethodInfo Method(Type type, string name, Func<MethodInfo, bool> predicate = null)
        {
            var method = type.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance)
                .Where(m => m.Name == name && (predicate == null || predicate(m)))
                .OrderBy(m => m.GetParameters().Length).FirstOrDefault();
            if (method == null) throw new MissingMethodException(type.FullName, name);
            return method;
        }
    }

    public static class Assets
    {
        public static void Import()
        {
            Core.Run((p, r) =>
            {
                var items = p.arguments.paths ?? new[] { p.arguments.path };
                foreach (var item in items.Where(x => !String.IsNullOrEmpty(x)))
                    AssetDatabase.ImportAsset(item, ImportAssetOptions.ForceSynchronousImport | ImportAssetOptions.ForceUpdate);
                r.artifacts = items.Where(x => !String.IsNullOrEmpty(x)).ToArray();
                r.message = "assets imported";
            });
        }
    }

    public static class Rendering
    {
        public static void CompileShaders()
        {
            Core.Run((p, r) =>
            {
                var items = p.arguments.paths ?? new[] { p.arguments.path };
                foreach (var item in items.Where(x => !String.IsNullOrEmpty(x)))
                    AssetDatabase.ImportAsset(item, ImportAssetOptions.ForceSynchronousImport | ImportAssetOptions.ForceUpdate);
                r.artifacts = items.Where(x => !String.IsNullOrEmpty(x)).ToArray();
                r.message = "shader assets synchronously imported and compiled";
            });
        }

        public static void BakeLighting()
        {
            Core.Run((p, r) =>
            {
                if (!Lightmapping.Bake()) throw new InvalidOperationException("Lightmapping.Bake returned false.");
                r.message = "lighting baked";
            });
        }
    }

    public static class Build
    {
        public static void SwitchPlatform()
        {
            Core.Run((p, r) =>
            {
                BuildTarget target;
                if (!Enum.TryParse(p.arguments.target, true, out target))
                    throw new InvalidOperationException("Unknown BuildTarget: " + p.arguments.target);
                var group = BuildPipeline.GetBuildTargetGroup(target);
                if (!EditorUserBuildSettings.SwitchActiveBuildTarget(group, target))
                    throw new InvalidOperationException("SwitchActiveBuildTarget returned false.");
                r.message = "platform switched to " + target;
            });
        }

        public static void BuildPlayer()
        {
            Core.Run((p, r) =>
            {
                BuildTarget target;
                if (!Enum.TryParse(p.arguments.target, true, out target))
                    throw new InvalidOperationException("Unknown BuildTarget: " + p.arguments.target);
                var scenes = p.arguments.scenes == null || p.arguments.scenes.Length == 0
                    ? EditorBuildSettings.scenes.Where(s => s.enabled).Select(s => s.path).ToArray()
                    : p.arguments.scenes;
                if (String.IsNullOrEmpty(p.arguments.output_path))
                    throw new InvalidOperationException("arguments.output_path is required.");
                var report = BuildPipeline.BuildPlayer(new BuildPlayerOptions
                {
                    scenes = scenes,
                    locationPathName = p.arguments.output_path,
                    target = target,
                    options = (BuildOptions)p.arguments.options
                });
                if (report.summary.result != BuildResult.Succeeded)
                    throw new InvalidOperationException("Build failed: " + report.summary.result);
                r.artifacts = new[] { p.arguments.output_path };
                r.message = "player built";
            });
        }
    }

    public static class Addressables
    {
        public static void BuildContent()
        {
            Core.Run((p, r) =>
            {
                var type = Core.TypeByName("UnityEditor.AddressableAssets.Settings.AddressableAssetSettings");
                Core.Method(type, "BuildPlayerContent", m => m.IsStatic && m.GetParameters().Length == 0).Invoke(null, null);
                r.message = "Addressables content built";
            });
        }

        public static void Analyze()
        {
            Core.Run((p, r) =>
            {
                var system = Core.TypeByName("UnityEditor.AddressableAssets.Build.AnalyzeSystem.AnalyzeSystem");
                var ruleBase = Core.TypeByName("UnityEditor.AddressableAssets.Build.AnalyzeRules.AnalyzeRule");
                var rules = AppDomain.CurrentDomain.GetAssemblies().SelectMany(a =>
                    {
                        try { return a.GetTypes(); }
                        catch { return new Type[0]; }
                    })
                    .Where(t => !t.IsAbstract && ruleBase.IsAssignableFrom(t) &&
                        (String.IsNullOrEmpty(p.arguments.rule_name) ||
                         t.FullName.IndexOf(p.arguments.rule_name, StringComparison.OrdinalIgnoreCase) >= 0)).ToArray();
                var refresh = Core.Method(system, "RefreshAnalysis", m => m.IsStatic && m.GetParameters().Length == 1);
                foreach (var rule in rules) refresh.Invoke(null, new[] { Activator.CreateInstance(rule) });
                r.artifacts = rules.Select(t => t.FullName).ToArray();
                r.message = "Addressables analyze rules refreshed";
            });
        }

        public static void CreateGroup()
        {
            Core.Run((p, r) =>
            {
                var settings = Core.AddressableSettings();
                var type = settings.GetType();
                var method = Core.Method(type, "CreateGroup", m => !m.IsStatic && m.GetParameters().Length >= 4);
                var ps = method.GetParameters();
                var args = new object[ps.Length];
                for (var i = 0; i < ps.Length; i++)
                    args[i] = ps[i].ParameterType == typeof(string) ? p.arguments.group_name
                        : ps[i].ParameterType == typeof(bool) ? (object)(i == 3)
                        : ps[i].ParameterType.IsArray ? Array.CreateInstance(ps[i].ParameterType.GetElementType(), 0)
                        : null;
                var group = method.Invoke(settings, args);
                if (group == null) throw new InvalidOperationException("CreateGroup returned null.");
                r.message = "Addressables group created";
            });
        }

        public static void DeleteGroup()
        {
            Core.Run((p, r) =>
            {
                var settings = Core.AddressableSettings();
                var find = Core.Method(settings.GetType(), "FindGroup", m => m.GetParameters().Length == 1);
                var group = find.Invoke(settings, new object[] { p.arguments.group_name });
                if (group == null) throw new InvalidOperationException("Addressables group not found.");
                Core.Method(settings.GetType(), "RemoveGroup", m => m.GetParameters().Length == 1)
                    .Invoke(settings, new[] { group });
                r.message = "Addressables group deleted";
            });
        }

        public static void ConfigureSchema()
        {
            Core.Run((p, r) =>
            {
                var settings = Core.AddressableSettings();
                var group = Core.Method(settings.GetType(), "FindGroup", m => m.GetParameters().Length == 1)
                    .Invoke(settings, new object[] { p.arguments.group_name });
                if (group == null) throw new InvalidOperationException("Addressables group not found.");
                var schemaType = Core.TypeByName(p.arguments.schema_type);
                Core.Method(group.GetType(), "AddSchema",
                        m => m.GetParameters().Length == 1 && m.GetParameters()[0].ParameterType == typeof(Type))
                    .Invoke(group, new object[] { schemaType });
                r.message = "Addressables schema configured";
            });
        }

        public static void ConfigureProfile()
        {
            Core.Run((p, r) =>
            {
                var settings = Core.AddressableSettings();
                var profileSettings = settings.GetType().GetProperty("profileSettings").GetValue(settings, null);
                var profileId = Core.Method(profileSettings.GetType(), "GetProfileId", m => m.GetParameters().Length == 1)
                    .Invoke(profileSettings, new object[] { p.arguments.profile_name });
                var variableId = Core.Method(profileSettings.GetType(), "GetVariableId", m => m.GetParameters().Length == 1)
                    .Invoke(profileSettings, new object[] { p.arguments.variable_name });
                Core.Method(profileSettings.GetType(), "SetValue", m => m.GetParameters().Length == 3)
                    .Invoke(profileSettings, new[] { profileId, variableId, p.arguments.value });
                r.message = "Addressables profile configured";
            });
        }
    }

    public static class TwoD
    {
        public static void BakeSpriteShape()
        {
            Core.Run((p, r) =>
            {
                throw new NotSupportedException("SpriteShape bake requires a package-specific bridge extension.");
            });
        }
    }

    public static class ThreeD
    {
        public static void ApplyProBuilder()
        {
            Core.Run((p, r) =>
            {
                throw new NotSupportedException("ProBuilder apply requires a package-specific bridge extension.");
            });
        }
    }
}
#endif
